export default {
    POPPINS_BLACK: 'Poppins-Black',
    POPPINS_BOLD_ITALIC: 'Poppins-ExtraBoldItalic',
    POPPINS_ITALIC: 'Poppins-LightItalic',
    POPPINS_SEMI_BOLD_ITALIC: 'Poppins-SemiBoldItalic',
    POPPINS_BLACK_ITALIC: 'Poppins-BlackItalic',
    POPPINS_EXTRA_LIGHT: 'Poppins-ExtraLight',
    POPPINS_MEDIUM: 'Poppins-Medium',
    POPPINS_THIN: 'Poppins-Thin',
    POPPINS_BOLD: 'Poppins-Bold',
    POPPINS_EXTRA_LIGHT_ITALIC: 'Poppins-ExtraLightItalic',
    POPPINS_MEDIUM_ITALIC: 'Poppins-MediumItalic',
    POPPINS_THIN_ITALIC: 'Poppins-ThinItalic',
    POPPINS_BOLD_ITALIC: 'Poppins-BoldItalic',
    POPPINS_ITALIC: 'Poppins-Italic',
    POPPINS_REGULAR: 'Poppins-Regular',
    POPPINS_EXTRA_BOLD: 'Poppins-ExtraBold',
    POPPINS_LIGHT: 'Poppins-Light',
    POPPINS_SEMI_BOLD: 'Poppins-SemiBold',
}
